import streamlit as st
import os

st.set_page_config(page_title="DeepSeek Scratch: GPT-2 Training", layout="wide")

st.title("DeepSeek Scratch: GPT-2 Training Dashboard")
st.markdown("This dashboard displays the training progress, loss curves, and HellaSwag evaluation metrics for the GPT-2 from-scratch implementation.")

# Define paths
LOG_FILE = "log/log.txt"
TRAIN_PLOT = "log/training_plot.png"

# Sidebar
st.sidebar.header("Training Progress")
if os.path.exists(LOG_FILE):
    st.sidebar.success("Log file found.")
    
    # Parse latest logs for sidebar
    with open(LOG_FILE, "r") as f:
        lines = f.readlines()
        
    latest_step = "N/A"
    latest_train_loss = "N/A"
    latest_val_loss = "N/A"
    latest_hella = "N/A"
    
    for line in reversed(lines):
        parts = line.strip().split()
        if len(parts) == 3:
            step, stream, val = parts
            if step != "step":
                if stream == "train" and latest_train_loss == "N/A":
                    latest_step = step
                    latest_train_loss = val
                elif stream == "val" and latest_val_loss == "N/A":
                    latest_val_loss = val
                elif stream == "hella" and latest_hella == "N/A":
                    latest_hella = val
                    
    st.sidebar.metric(label="Latest Step", value=latest_step)
    st.sidebar.metric(label="Train Loss", value=latest_train_loss)
    st.sidebar.metric(label="Validation Loss", value=latest_val_loss)
    st.sidebar.metric(label="HellaSwag Acc", value=latest_hella)
else:
    st.sidebar.warning("Log file not found. Have you started training?")

# Main content
tab1, tab2, tab3 = st.tabs(["Training Graphs", "Raw Logs", "Architecture"])

with tab1:
    st.header("Training Graphs")
    st.markdown("These graphs are generated by the `log.ipynb` script after a full training run.")
    if os.path.exists(TRAIN_PLOT):
        st.image(TRAIN_PLOT, caption="Training and Validation Metrics")
    else:
        st.info("Training plot not found. Run `log.ipynb` to generate `log/training_plot.png`.")

with tab2:
    st.header("Raw Log Data")
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, "r") as f:
            log_content = f.read()
        st.text_area("log/log.txt contents", log_content, height=400)
    else:
        st.info("Log file is empty or missing.")

with tab3:
    st.header("GPT-2 Architecture Diagram")
    st.markdown("""
```mermaid
graph TD
    InputTokens[Input Tokens] --> WTE[Token Embedding]
    InputPos[Positions] --> WPE[Positional Embedding]
    WTE --> Add1((+))
    WPE --> Add1
    Add1 --> Block1
    
    subgraph Transformer Blocks [x12 Layers]
        Block1[Input] --> LN1[LayerNorm]
        LN1 --> Attn[Causal Self-Attention]
        Attn --> Add2((+))
        Block1 --> Add2
        Add2 --> LN2[LayerNorm]
        LN2 --> MLP[MLP w/ GELU]
        MLP --> Add3((+))
        Add2 --> Add3
    end
    
    Add3 --> FinalLN[Final LayerNorm]
    FinalLN --> LMHead[Linear LM Head]
    LMHead --> Logits[Vocabulary Logits]
```
""")
